version: '3.8'

services:
  app:
    image: noivira124/tendee-naila
    container_name: tendee-service
    ports:
      - "3011:3011"
    environment:
      - PORT=3011
      - JWT_SECRET=tendee-super-secret-jwt-key
    volumes:
      # Menghubungkan file database di root aplikasi ke folder di STB
      - ~/tendee-data/database.sqlite:/app/database.sqlite
    restart: always